//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRequest.db {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class tServers : ActiveRecordBase<tServers> {
        
        private int _iD_Servers;
        
        private string _nameServer;
        
        private string _serverIP;
        
        private short _port;
        
        private string _method;
        
        private string _servers_Description;
        
        private string _servers_Other;
        
        private byte[] _fileForExtension;
        
        private string _requestLine;
        
        private string _protocol;
        
        private string _password;
        
        private string _fileName;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int ID_Servers {
            get {
                return this._iD_Servers;
            }
            set {
                this._iD_Servers = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string NameServer {
            get {
                return this._nameServer;
            }
            set {
                this._nameServer = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string ServerIP {
            get {
                return this._serverIP;
            }
            set {
                this._serverIP = value;
            }
        }
        
        [Property(ColumnType="Int16")]
        public virtual short Port {
            get {
                return this._port;
            }
            set {
                this._port = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Method {
            get {
                return this._method;
            }
            set {
                this._method = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Servers_Description {
            get {
                return this._servers_Description;
            }
            set {
                this._servers_Description = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Servers_Other {
            get {
                return this._servers_Other;
            }
            set {
                this._servers_Other = value;
            }
        }
        
        [Property(ColumnType="BinaryBlob")]
        public virtual byte[] FileForExtension {
            get {
                return this._fileForExtension;
            }
            set {
                this._fileForExtension = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string RequestLine {
            get {
                return this._requestLine;
            }
            set {
                this._requestLine = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Protocol {
            get {
                return this._protocol;
            }
            set {
                this._protocol = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Password {
            get {
                return this._password;
            }
            set {
                this._password = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string FileName {
            get {
                return this._fileName;
            }
            set {
                this._fileName = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tInfo : ActiveRecordBase<tInfo> {
        
        private int _iD_Info;
        
        private string _version_DB;
        
        private string _info_Description;
        
        private string _info_Other;
        
        private byte[] _fileForExtension;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int ID_Info {
            get {
                return this._iD_Info;
            }
            set {
                this._iD_Info = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Version_DB {
            get {
                return this._version_DB;
            }
            set {
                this._version_DB = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Info_Description {
            get {
                return this._info_Description;
            }
            set {
                this._info_Description = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Info_Other {
            get {
                return this._info_Other;
            }
            set {
                this._info_Other = value;
            }
        }
        
        [Property(ColumnType="BinaryBlob")]
        public virtual byte[] FileForExtension {
            get {
                return this._fileForExtension;
            }
            set {
                this._fileForExtension = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tHeader_Params : ActiveRecordBase<tHeader_Params> {
        
        private int _iD_Header_Params;
        
        private string _templateParametrs;
        
        private string _header_Params_Description;
        
        private string _header_Params_Other;
        
        private byte[] _fileForExtension;
        
        private string _nameTemplate;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int ID_Header_Params {
            get {
                return this._iD_Header_Params;
            }
            set {
                this._iD_Header_Params = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string TemplateParametrs {
            get {
                return this._templateParametrs;
            }
            set {
                this._templateParametrs = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Header_Params_Description {
            get {
                return this._header_Params_Description;
            }
            set {
                this._header_Params_Description = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Header_Params_Other {
            get {
                return this._header_Params_Other;
            }
            set {
                this._header_Params_Other = value;
            }
        }
        
        [Property(ColumnType="BinaryBlob")]
        public virtual byte[] FileForExtension {
            get {
                return this._fileForExtension;
            }
            set {
                this._fileForExtension = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string NameTemplate {
            get {
                return this._nameTemplate;
            }
            set {
                this._nameTemplate = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tHeaderTemplate : ActiveRecordBase<tHeaderTemplate> {
        
        private int _iD_Header_Template;
        
        private string _serverLine;
        
        private string _headerLine;
        
        private string _header_Description;
        
        private byte[] _fileForExtension;
        
        private string _serverPassword;
        
        private string _header_Other;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int ID_Header_Template {
            get {
                return this._iD_Header_Template;
            }
            set {
                this._iD_Header_Template = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string ServerLine {
            get {
                return this._serverLine;
            }
            set {
                this._serverLine = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string HeaderLine {
            get {
                return this._headerLine;
            }
            set {
                this._headerLine = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Header_Description {
            get {
                return this._header_Description;
            }
            set {
                this._header_Description = value;
            }
        }
        
        [Property(ColumnType="BinaryBlob")]
        public virtual byte[] FileForExtension {
            get {
                return this._fileForExtension;
            }
            set {
                this._fileForExtension = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string ServerPassword {
            get {
                return this._serverPassword;
            }
            set {
                this._serverPassword = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Header_Other {
            get {
                return this._header_Other;
            }
            set {
                this._header_Other = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tPayLoad_Scenario : ActiveRecordBase<tPayLoad_Scenario> {
        
        private int _iD_PayLoad_Scenario;
        
        private tPayLoadData _tPayLoadData;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int ID_PayLoad_Scenario {
            get {
                return this._iD_PayLoad_Scenario;
            }
            set {
                this._iD_PayLoad_Scenario = value;
            }
        }
        
        [Nested(Insert=true, Update=true)]
        public virtual tPayLoadData tPayLoadData {
            get {
                return this._tPayLoadData;
            }
            set {
                this._tPayLoadData = value;
            }
        }
    }
    
    public partial class tPayLoadData {
        
        private string _payLoad_Content;
        
        private string _payLoad_Description;
        
        private string _payLoad_Other;
        
        private byte[] _fileForExtension;
        
        private string _payLoad_Name;
        
        [Property(ColumnType="String")]
        public virtual string PayLoad_Content {
            get {
                return this._payLoad_Content;
            }
            set {
                this._payLoad_Content = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string PayLoad_Description {
            get {
                return this._payLoad_Description;
            }
            set {
                this._payLoad_Description = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string PayLoad_Other {
            get {
                return this._payLoad_Other;
            }
            set {
                this._payLoad_Other = value;
            }
        }
        
        [Property(ColumnType="BinaryBlob")]
        public virtual byte[] FileForExtension {
            get {
                return this._fileForExtension;
            }
            set {
                this._fileForExtension = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string PayLoad_Name {
            get {
                return this._payLoad_Name;
            }
            set {
                this._payLoad_Name = value;
            }
        }
    }
    
    public class TestRequest_DBHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(tServers),
                    typeof(tInfo),
                    typeof(tHeader_Params),
                    typeof(tHeaderTemplate),
                    typeof(tPayLoad_Scenario)};
        }
    }
}
